### ISSUE TITLE
Unable to parse JSON string: node_modules/nodepdf/render.js:16

### ISSUE THREAD

**Issue by cuva** [TJkrusinski/NodePDF#33]
Hi,

I'm having issues generating a PDF that actually embeds proper HTML.

My code works for a options.content = '<p> This is the body </p>' but it starts breaking as soon as i'm embedding a slightly more complicated HTML.

i.e, only setting the content to: '<p class="toto">This is the body</p>' makes it break with the above mentioned error.

It also breaks if I use the following example displayed on the home page:

```
var PDF = new NodePDF(null, 'google.pdf', {
    'content': '<html><body><img src="https://www.google.com/images/srpr/logo11w.png" alt="google"/></body></html>',
    'viewportSize': {
      'width': 1440,
      'height': 900
    }
})
```

Do you know what the issue is?
Many thanks

**Comment by cyates81** [comment]
Hello,

I am using version 1.2 and am experiencing a similar issue.  I have HTML content that when it contains an apostrophe it works.  If I remove the apostrophe I get this error.

I am using this code to generate:
```
var pdf = new NodePDF(null, 'test.pdf', {
          'content': html,
          'paperSize': {
            'format': 'Letter',
            'footer': {
              'height': '1cm',
              'contents': '<table style="font-size: smaller; width: 100%;"><tr><td style="width: 25%;"></td><td style="width: 50%; text-align: center;">Canton Municipal Court, Civil Division</td><td style="text-align: right;">Page {currentPage} of {pages}</td></tr></table>'
            }
          }
        });
```
This html works:

```
<html><head></head><body>Testing with apostrophe '</body></html>
```

This html doesn't:
```
<html><head></head><body>Testing without apostrophe</body></html>
```
